language: ruby
rvm:
  - 1.9.3
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle version
  - bundle update debugger
  - bundle update sqlite3
before_script:
  - ls
  - cp config/application.yml.example config/application.yml
  - cp config/database.yml.travis-ci config/database.yml
  - cp config/epic.yml.example config/epic.yml
  - cp config/ldap.yml.example config/ldap.yml
  - tail config/database.yml
  - tail config/database.yml.travis-ci
script:
  - rake db:test:load
  - bundle exec rspec spec/mailers
  - bundle exec rspec spec/models
  - bundle exec rspec spec/controllers