language: ruby
rvm:
  - 1.9.3
before_install:
  - bundle update debugger
  - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa && sudo apt-get update && sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/application.yml.example config/application.yml
  - cp config/epic.yml.example config/epic.yml
  - cp config/ldap.yml.example config/ldap.yml
script:
  - bundle exec rspec