sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9.3
env:
  - DATABASE_URL=sqlite3:///":memory:"
before_install:
  - gem update --system
  - gem --version
  - gem install sqlite3
  - gem install bundler
  - bundle version
  - bundle update debugger
  - bundle update sqlite3
before_script:
  - cp config/database.yml.travis-ci config/database.yml
  - tail config/database.yml
  - cp config/application.yml.example config/application.yml
  - cp config/epic.yml.example config/epic.yml
  - cp config/ldap.yml.example config/ldap.yml
script:
  - RAILS_ENV=test bundle exec rake db:test:load
  - RAILS_ENV=test bundle exec rspec spec/mailers
  - RAILS_ENV=test bundle exec rspec spec/models
  - RAILS_ENV=test bundle exec rspec spec/controllers