sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9.3
before_install:
  - bundle update debugger  
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/application.yml.example config/application.yml
  - cp config/epic.yml.example config/epic.yml
  - cp config/ldap.yml.example config/ldap.yml
script:
# a collection of tests that should pass
  - bundle exec rspec spec/api spec/helpers spec/lib spec/mailers spec/support spec/controllers/portal/*security* spec/models/protocol_authorizer_spec.rb spec/models/sub_service_request/ready_for_fulfillment_spec.rb spec/models/pricing_map_spec.rb 
