sudo: false
language: ruby
cache: bundler
before_install:
  - export TZ=America/New_York
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cp config/database.yml.example config/database.yml
  - cp config/application.yml.example config/application.yml
  - cp config/epic.yml.example config/epic.yml
  - cp config/ldap.yml.example config/ldap.yml
  - mysql -e 'create database test_sparc_request;'
script:
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make
  - RAILS_ENV=test bundle exec rake db:migrate 
  - bundle exec rspec 
