language: ruby
rvm:
  - 1.9.3
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle version
  - bundle update debugger
  - bundle update sqlite3
before_script:
  - cp config/application.yml.example config/application.yml
  - cp config/database.yml.travis-ci config/database.yml
  - cp config/epic.yml.example config/epic.yml
  - cp config/ldap.yml.example config/ldap.yml
  - tail config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:test:prepare	
  - RAILS_ENV=test bundle exec rspec spec/mailers
  - RAILS_ENV=test bundle exec rspec spec/models
  - RAILS_ENV=test bundle exec rspec spec/controllers