sudo: false
language: ruby
cache: bundler
before_install:
  - export TZ=America/New_York
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cp config/database.yml.example config/database.yml
  - cp config/application.yml.example config/application.yml
  - cp config/epic.yml.example config/epic.yml
  - cp config/ldap.yml.example config/ldap.yml
  - mysql -e 'create database test_sparc_request;'
  - RAILS_ENV=test bundle exec rake db:migrate
jobs:
  include:
    - script: bundle exec rspec spec/api
    - script: bundle exec rspec spec/extensions
    - script: bundle exec rspec spec/jobs
    - script: bundle exec rspec spec/helpers
    - script: bundle exec rspec spec/mailers
    - script: bundle exec rspec spec/controllers
    - script: bundle exec rspec spec/features
    - script: bundle exec rspec spec/lib
    - script: bundle exec rspec spec/models
    - script: bundle exec rspec spec/views
