protocol:
  step_text: 'STEP 1: Review Services and Assign Study or Project'
  css_class: blue-provider
  back: catalog
  catalog: catalog
  forward: service_details
  validation_groups: 
    catalog:
    save_and_exit:
      - protocol
    service_details:
      - protocol

service_details:
  step_text: 'STEP 2: Enter Service Details'
  css_class: light-blue-provider
  back: protocol
  catalog: catalog
  forward: service_calendar
  validation_groups:
    catalog:
      - service_details_back
    protocol:
      - service_details_back
    save_and_exit:
      - service_details_back
    service_calendar:
      - service_details

service_calendar:
  step_text: 'STEP 2: Visit Calendar'
  css_class: light-blue-provider
  back: service_details 
  catalog: catalog
  forward: calendar_totals
  validation_groups:
    service_subsidy:

calendar_totals:
  step_text: 'STEP 2: Calendar Totals'
  css_class: light-blue-provider
  back: service_calendar
  catalog: catalog
  forward: service_subsidy
  validation_groups:
    service_subsidy:

service_subsidy:
  step_text: 'STEP 2: Enter Subsidy Information'
  css_class: light-blue-provider
  back: calendar_totals
  catalog: catalog
  forward: document_management 
  validation_groups:
    document_management:
      - service_subsidy

document_management:
  step_text: 'STEP 3: Additional Notes and Information'
  css_class: orange-provider
  back: service_subsidy
  catalog: catalog
  forward: review
  validation_groups:
    review_view:
      - document_management

review:
  step_text: 'STEP 4: Review Your Request'
  css_class: red-provider
  back: document_management 
  catalog: catalog
  obtain_research_pricing: obtain_research_pricing
  forward: confirmation
  validation_groups:
    document_management:

obtain_research_pricing:
  step_text: 'STEP 5a: Obtain Research Pricing'
  css_class: green-provider
  back: review 
  catalog: catalog
  validation_groups:
    document_management:

confirmation:
  step_text: 'STEP 5: Submission Confirmation'
  css_class: green-provider
  back: review 
  catalog: catalog
  forward: confirmation
  validation_groups:
    document_management:
