protocol:
  step_text: 'STEP 1: Review Services and Assign Study or Project'
  css_class: blue-provider
  back: catalog
  catalog: catalog
  forward: service_details
  validation_groups: 
    catalog:
    service_details:
      - protocol

service_details:
  step_text: 'STEP 2: Enter Service Details'
  css_class: light-blue-provider
  back: protocol
  catalog: catalog
  forward: service_calendar
  validation_groups:
    protocol:
      - protocol
    service_calendar:
      - service_details
      - protocol

service_calendar:
  step_text: 'STEP 2: Visit Calendar'
  css_class: light-blue-provider
  back: service_details 
  catalog: catalog
  forward: review
  validation_groups:
    protocol:
      - service_details
      - protocol
    service_details:
      - service_details
      - protocol
    service_details:
    service_subsidy:

review:
  step_text: 'STEP 4: Review Your Request'
  css_class: red-provider
  back: protocol
  catalog: catalog
  forward: confirmation